import type { Metadata } from "next";
import { Almarai } from "next/font/google";
import "./globals.css";

const almarai = Almarai({
  subsets: ["arabic"],
  weight: ["300", "400", "700", "800"], // الأوزان المطلوبة
});

export const metadata: Metadata = {
  title: "Toursim App",
  description: "Generated by Mohamed Hossam",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" className="bg-white">
      <body className={almarai.className}>
        {children}
      </body>
    </html>
  );
}
